In [ ]:
#The selling price of 3 items at the bake sale are: $2 for a brownie, $1 for a cookie, $10 for a cake.

In [ ]:
price=[2, 1, 10]
type(price)

list

In [ ]:
#The club sells 17 brownies, 40 cookies, and 1 cake. 

In [ ]:
quantity_sold=[17, 40, 1]
type(quantity_sold)

list

In [ ]:
#Importing the NumPy library & Converting a list to a NumPy Array

In [ ]:
import numpy as np
price_array=np.array(price)
quantity_sold_array=np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [ ]:
#We want the price * quantity for each item. Let's try multiplying our arrays.

In [ ]:
price_array * quantity_sold_array

array([34, 40, 10])

In [ ]:
 #Let's say a brownie costs $0.25 to make, a cookie costs $0.50 to make, and a cake costs $5.00 to make.

In [ ]:
cost_array=np.array([0.25, 0.50, 5.00])
profit_array=price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


In [ ]:
#The output is the profit made for each item type.  For example, each Brownie makes the club a profit of $1.75.

In [ ]:
#Suppose you wanted to identify which items made a profit greater than $2 per item.

In [ ]:
profit_array>2

array([False, False,  True])

In [ ]:
#Appending, Deleting
#The club will also sell pies for $7 so we need to update our price_array

In [ ]:
#INCORRECT WHEN + 7

In [ ]:
price_array = price_array + [7]
print(price_array)

[ 9  8 17]


In [ ]:
price_array = price_array - [7]
print(price_array)

[ 2  1 10]


In [ ]:
# Append to array - # The proper way to append an element to an array

In [ ]:
price_array = np.append(price_array, 7)
print(price_array)

[ 2  1 10  7]


In [ ]:
#the club want to add the following prices:  $4.50 for fudge, $3 for a cupcake, $4 for a loaf of banana bread, and $9 for a torte.

In [ ]:
price_array = np.append(price_array, [4.50, 3, 4, 9])
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [ ]:
#o check the data type of elements within the array, you can use the following:

In [ ]:
print(price_array.dtype)

float64


In [ ]:
#It turns out nobody plans to make a torte, so they want to remove the price of that item from the array. 

In [ ]:
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [ ]:
#Next the club decides to raise the price of cakes from $10 to $12. (Cakes are at index 2.)

In [ ]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


In [ ]:
#2) Update the  quantity_sold_array to include the sale of 2 pies,  3 trays of fudge, 16 cupcakes, and 5 loaves of banana bread.   

In [ ]:
quantity_sold_array = np.append(quantity_sold_array, [2, 3, 16, 5])
print(quantity_sold_array)

[17 40  1  2  3 16  5]


In [ ]:
#One of the cookies fallen on the ground, so edit the quantity_sold_array from 40 to 39.

In [ ]:
quantity_sold_array[1] = 39
print(quantity_sold_array)

[17 39  1  2  3 16  5]


In [ ]:
#Determine the amount of money collected from the sale of each item at the bake sale.  

In [ ]:
price_array * quantity_sold_array

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

In [ ]:
#4) Create a NumPy array "quantity_leftover" that includes the quantity of each item remaining at the end of the sale: 2 cakes, 1 pie, 6 trays of fudge, 2 loaves of banana bread.  Hint: Make sure to include "0" for any item that was sold out. Why is this important when creating the array?

In [ ]:
quantity_leftover=[0, 0, 2, 1, 6, 2]
type(quantity_leftover)

list

In [ ]:
quantity_leftover_array=np.array(quantity_leftover)

In [ ]:
#5) The club decides to sell the leftover items at half price and everything quickly sells out!  Determine how much money was collected from the clearance sale.  

In [ ]:
price_array / 2

array([1.  , 0.5 , 6.  , 3.5 , 2.25, 1.5 , 2.  ])

In [ ]:
#6) How much total money was collected from the bake sale (including the sale of full price and clearance items)?

In [ ]:
quantity_leftover_array=np.array([0, 0, 2, 1, 6, 0, 2])
(price_array / 2) * quantity_leftover_array

array([ 0. ,  0. , 12. ,  3.5, 13.5,  0. ,  4. ])

In [ ]:
([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])+ ([ 0. ,  0. , 12. ,  3.5, 13.5,  0. ,  4. ])

[34.0, 39.0, 12.0, 14.0, 13.5, 48.0, 20.0, 0.0, 0.0, 12.0, 3.5, 13.5, 0.0, 4.0]

In [ ]:
import numpy as np
np.sum([34.0, 39.0, 12.0, 14.0, 13.5, 48.0, 20.0, 0.0, 0.0, 12.0, 3.5, 13.5, 0.0, 4.0])

213.5

In [ ]:
# Hint: Your final answer should be $213.50, but you must make sure you get this answer with your NumPy coding skills!!